### ISSUE TITLE
Failed to start com.webmr.exokit .fullscreen 

### ISSUE THREAD

**Issue by RealBBakGosu** [exokitxr/exokit#1410] opened 2019-09-02 07:59 UTC
Hello.

I installed exokit.mpk using mabu --re-sign and chang the certification to my own cuz the Existing cert is not available and the mpk is installed successfully  but when I launch the app with [mldb launch com.webmr.exokit -v "ARGS=node . file:///package/examples/hello_ml.html" ] command 
The app does not behave normally. When I used it without the -v option, I checked that the app works. What is the problem?

![sdfsdfsdfsdfsdf](https://user-images.githubusercontent.com/52807219/64098866-e4e32c00-cda2-11e9-9c32-10ce0123eaaf.JPG)

**Comment by modulesio** [comment] 2019-09-02 16:10
We don’t support re-signing mpks — the app should be rebuilt instead. But most likely the problem is the debuggable flag was not set on the re-sign.

**Comment by modulesio** [comment] 2019-09-03 15:14
Closing this one as resolved — please re-open if that’s not the case!

**Closed by modulesio** 2019-09-03 15:14 UTC
