### ISSUE TITLE
Load Moon Rider in Exokit

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit#1078] opened 2019-05-21 04:24 UTC
Windows 10
Node v12.2.0
`user-parallel` branch of Exokit
site url: https://moonrider.xyz/

command ran: `$ node --experimental-worker . -h -t https://moonrider.xyz/`

[View full log in gist](https://gist.github.com/chrisplatorres/30fb09b91595674740a0e4b5050739b7)

**Comment by modulesio** [comment] 2019-05-21 04:33
Thanks! I already see a few things like Worker `xmlhttprequest` require misnaming.

**Comment by modulesio** [comment] 2019-05-21 04:35
Looks like it's mostly getting stuck in the preload image phase.

**Comment by chrisplatorres** [comment] 2019-05-21 05:08
Thanks, the [require renaming](https://github.com/exokitxr/exokit/commit/63ef2340af3f5f33bdc332e340b9ea7103609315) fixed some of the errors, I notice now the moon rider audio is loading for a few seconds.

> Looks like it's mostly getting stuck in the preload image phase.
  
`[gpu-preloader] Error preloading, image not loaded s {`


Yes, where would I be looking for the preloading stage to be getting stuck in the engine?
  
----------------------------------------------------

```
TypeError: Cannot read property '1' of undefined
    at i.getDistance (build/build.js:180:68102)
    at i.tick (build/build.js:180:67699)
    at HTMLElement.value (vendor/aframe-master.min.js:255:11226)
    at HTMLElement.value (vendor/aframe-master.min.js:255:11760)
    at vendor/aframe-master.min.js:386:132
    at m (vendor/aframe-master.min.js:89:21552)
    at t (vendor/aframe-master.min.js:87:3246)
    at _renderLocal (C:\Users\chris\github\exokit\src\Window.js:1305:15)
    at window.tickAnimationFrame (C:\Users\chris\github\exokit\src\Window.js:1364:5)
    at global.onrunasync.method (C:\Users\chris\github\exokit\src\Window.js:1529:19)
```
https://github.com/exokitxr/exokit/blob/user-parallel/src/Window.js#L1529

```
TypeError: Cannot read property '0' of undefined
    at r.decompose (vendor/aframe-master.min.js:92:27113)
    at i.<anonymous> (vendor/aframe-master.min.js:170:4261)
    at i.tick (vendor/aframe-master.min.js:170:1525)
    at HTMLElement.value (vendor/aframe-master.min.js:255:11226)
    at HTMLElement.value (vendor/aframe-master.min.js:255:11760)
    at vendor/aframe-master.min.js:386:132
    at o (vendor/aframe-master.min.js:89:17145)
    at t (vendor/aframe-master.min.js:87:3246)
    at self.requestAnimationFrame.timestamp (C:\Users\chris\github\exokit\src\VR.js:4
36:11)
    at animationFrame.onrequestanimationframe.timestamp (C:\Users\chris\github\exokit
\src\VR.js:307:9)
```
https://github.com/exokitxr/exokit/blob/user-parallel/src/VR.js#L307
### [View full log in gist](https://gist.github.com/chrisplatorres/8f7f0684893d5c10b34685e4c1bf65e5)

**Comment by chrisplatorres** [comment] 2019-05-21 06:55
Source code for moonrider: https://github.com/supermedium/moonrider

**Comment by chrisplatorres** [comment] 2019-05-22 07:03
windows 10 audio error when running `master`: 

`node . -x webvr -t https://moonrider.xyz/`

```
[Vorbis parser @ 00000270919c7980] Invalid packet
[Vorbis parser @ 00000270919c7980] Invalid packet
[Vorbis parser @ 00000270919c7980] Invalid packet
[Vorbis parser @ 00000270919c7980] Invalid packet
[vorbis @ 0000027091a3b000] Not a Vorbis I audio packet.
failed to load audio: https://previews.moonrider.xyz/2588-song.ogg?v=1
ErrorEvent {
  type: 'error',
  target: <audio data-preview-start-time=0 src="https://previews.moonrider.xyz/2588-s
ong.ogg?v=1"></audio>,
  bubbles: false,
  cancelable: false,
  defaultPrevented: false,
  propagationStopped: false,
  currentTarget: <audio data-preview-start-time=0 src="https://previews.moonrider.xyz
/2588-song.ogg?v=1"></audio>,
  message: 'failed to decode audio: failed to decode packet (url: ' +
    '"https://previews.moonrider.xyz/2588-song.ogg?v=1", size: ' +
    '3604101)',
  stack: 'Error: failed to decode audio: failed to decode packet (url: ' +
    '"https://previews.moonrider.xyz/2588-song.ogg?v=1", size: ' +
    '3604101)\n    at C:\\Users\\chris\\github\\exokit\\src\\DOM.js:2729:25\n ' +
    '   at processTicksAndRejections ' +
    '(internal/process/task_queues.js:89:5)'
}
Error: failed to decode audio: failed to decode packet (url: "https://previews.moonri
der.xyz/2588-song.ogg?v=1", size: 3604101)
    at C:\Users\chris\github\exokit\src\DOM.js:2729:25
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

```

**Comment by modulesio** [comment] 2019-05-22 07:05
Is the above error only as a reality tab? Loading multiple audio contexts is bound to be iffier than loading a single one.

**Comment by chrisplatorres** [comment] 2019-05-22 07:06
Yes, it seems like it only happens when loaded as a tab.

**Comment by chrisplatorres** [comment] 2019-05-22 07:08
`node . -x webvr https://moonrider.xyz/`

Forces Exokit into fullscreen mode and opens a small second window?

**Comment by modulesio** [comment] 2019-05-22 07:09
I'm guessing there is a fullscreen API trigger in that case.

"Small second window" is probably a non-hidden canvas on the page.

**Comment by chrisplatorres** [comment] 2019-05-22 07:26
Got proper loading up and behavior up until clicking menus / selecting a song crashes. It seems there is a timing issue as it only loads successfully without crashing part of the time.
 


![wopCapture](https://user-images.githubusercontent.com/29695350/58153895-df1f6b80-7c35-11e9-8827-79aca97ca3e1.PNG)


Similar behavior for Quest:
https://youtu.be/xSC2tyuG458

the video looks great, but still need to:
- could have timing problem when launched that leads to crash
- clicking on song leads to crash
- a few menu UI bugs

**Comment by modulesio** [comment] 2019-05-22 22:42
For anyone else debugging this, you can get unminimized `moonrider` by editing `webpack.config.js`:

```
optimization: {
  minimize: false,
}
```

**Comment by modulesio** [comment] 2019-05-23 12:43
From my research there are two more classes of bug to fix here:

### Audio buffers

We have several outstanding issues for tracking `AudioBuffer` support in Exokit. This mostly has to do with GC references for the buffers, callbacks, and attachment points to the audio graph.

[`MediaElementAudioSourceNode`](https://developer.mozilla.org/en-US/docs/Web/API/MediaElementAudioSourceNode) also has to be changed to handle the case of reparenting from the default audio context to a custom `AudioContext`, as used by THREE.js.

Additionally, `GainNode` seems to be monaural even for stereo inputs, which is not correct.

### Asset loading races

Some of the VR entry and asset loading timing is off for A-Frame, resulting in missing binding crashes.

I think this has to do with Exokit being eager to enter XR and/or not emitting DOM load events in the expected order, which leads to incorrect code flow.

If we get lucky and the stars (moons) align we get entry into `moonrider` as Chris demonstrated, but we'll need to debug + fix these to make it reliable.

**Comment by modulesio** [comment] 2019-05-24 00:24
Previous useful AudioBuffer debugging work: https://github.com/exokitxr/exokit/commit/c2cb03d524a9235b56226051ba0e671c97b6bda7

**Comment by modulesio** [comment] 2019-05-24 00:26
One current blocker is that `AudioBuffer` loading [is synchronous](https://github.com/exokitxr/exokit/blob/15e446f5378f3d5bd10160a8762d8d0d31b65ada/deps/exokit-bindings/webaudiocontext/src/AudioContext.cpp#L168).

As far as I can tell there's no good reason for this, and it will hitch the main thread and make things like MoonRider lag. I'll make that async before moving onto why `AudioBuffer` gc is crashing.

**Comment by modulesio** [comment] 2019-05-24 13:01
I posted in the discord, but the [Application Verifier](https://docs.microsoft.com/en-us/windows/desktop/win7appqual/application-verifier) from Microsoft has really helped debugging memory corruptions here.

It seems to set a great deal of useful memory instrumentation at the cost of performance, but it really helps in cases where something is scribbling memory and you are struggling for a reliable reproduction.

**Comment by modulesio** [comment] 2019-05-24 16:09
The status with https://github.com/exokitxr/exokit/pull/1100/files is no more crashes! But there is still some audio glitching to handle:

- `GainNode` flattens the stereo channels to mono
- `HTMLAudioElement` wrapped in `SourceNode` will pull streams from both default and new contexts, resulting in half of samples thrown away
- For some reason clicking through into a song will not start the ride, even thought the audio load succeeds

**Comment by modulesio** [comment] 2019-05-26 04:39
Note: `gtags` presence in MoonRider causes asset loading failure running on Exokit.

**Comment by modulesio** [comment] 2019-05-26 05:45
`dmarcos` has a hacked branch that gets us reliably completing the load process:  https://github.com/supermedium/moonrider/compare/master...dmarcos:delayRenderLoop

**Comment by modulesio** [comment] 2019-05-26 16:43
With https://github.com/exokitxr/exokit/pull/1115, https://github.com/exokitxr/exokit/pull/1104, we get past the song beat loading.

However, that implementation uses `blob://` urls in `XMLHttpRequest`, so we will need to support that. (`fetch` already supports it)

**Comment by modulesio** [comment] 2019-05-26 16:51
To add `XMLHttpRequest` `Blob` support, we should patch [`window-xhr`](https://github.com/modulesio/window-xhr/tree/master/lib) to take `/^blob:\/\//` urls cached by Exokit's [`Blob` url capturing](https://github.com/exokitxr/exokit/blob/9adaf98941fc723595208a1fadc7110bd34ecf73/src/urls.js#L5).

I already confirmed the Blobs are captured but Moon Rider.

**Comment by modulesio** [comment] 2019-05-27 02:27
Blob support for `XMLHttpRequest` is here: https://github.com/modulesio/window-xhr/pull/4

**Comment by chrisplatorres** [comment] 2019-05-27 09:47
Great progress, no more timing issues and songs are loading from the menu. 🎶 

What I found when loading into latest APK:
- UI bugs in playlist menu (not seperating into columns? the black boxes are too far away from menu)
- UI bugs in genre menu (black boxes are too large and too far away from menu)
- Song titles and icons change on first screen, but clicks through only to the main menu songs
- Crash when searching (repro search "test" and select a song)
- Playing song stuck on loading screen (unpacking)

<details>
  <summary><h1>Click to expand image examples</h1></summary>
.

  
# UI bugs in playlist menu
![com webmr exokit-20190527-043110](https://user-images.githubusercontent.com/29695350/58411201-635c5f00-8039-11e9-8365-e9960da16d3e.jpg)
# UI bugs in genre menu
![com webmr exokit-20190527-043051](https://user-images.githubusercontent.com/29695350/58411200-635c5f00-8039-11e9-978e-18dc7f12cdb9.jpg)
# Song titles and icons change on first screen, but clicks through only to the main menu songs
![com webmr exokit-20190527-043124](https://user-images.githubusercontent.com/29695350/58411487-02815680-803a-11e9-82b2-ff8cb4ef24d1.jpg)
![com webmr exokit-20190527-043137](https://user-images.githubusercontent.com/29695350/58411488-0319ed00-803a-11e9-896f-26ffbcc289e9.jpg)
![com webmr exokit-20190527-043155](https://user-images.githubusercontent.com/29695350/58411489-0319ed00-803a-11e9-8597-921c50b3c12e.jpg)


</details>

**Comment by modulesio** [comment] 2019-05-27 12:14
Exokit should now be riding songs with the latest https://github.com/exokitxr/exokit/pull/1104.

![Capture 26](https://user-images.githubusercontent.com/6926057/58419015-6cf4bf80-8057-11e9-8488-baa7c28cf93b.PNG)

**Comment by chrisplatorres** [comment] 2019-05-27 22:06
in moon rider on quest on latest recompsite4 apk:
- missing block/beat hit sounds
- missing end of song "grade" sound
- missing end of song "grade" model (A, B, C, F, etc. grading)
- going to oculus home menu and then resuming resets to moon rider start screen

**Comment by modulesio** [comment] 2019-05-28 22:03
One thing I noticed when going for a ride is that the notes hit flow will log huge parts of the DOM, I think due to sound pool insufficiency:

```
components:sound:warn All the sounds are playing. If you need to play more sounds simultaneously consider increasing the size of pool with the `poolSize` attribute.  <a-entity id="beatContainer" beat-hit-sound="" bind__visible="isPlaying" sound__beathit1="" sound__beathit1left="" sound__beathit1right="" sound__beathit2="" sound__beathit2left="" sound__beathit2right="" sound__beathit3="" sound__beathit3left="" sound__beathit3right="" sound__beathit4="" sound__beathit4left="" sound__beathit4right="" sound__beathit5="" sound__beathit5left="" sound__beathit5right="" sound__beathit6="" sound__beathit6left="" sound__beathit6right="" sound__beathit7="" sound__beathit7left="" sound__beathit7right="" sound__beathit8="" sound__beathit8left="" sound__beathit8right="" sound__beathit9="" sound__beathit9left="" sound__beathit9right="" sound__beathit10="" sound__beathit10left="" sound__beathit10right="" visible="">
  <a-entity mixin="gameoverAnimation beat arrowBlueBeat" animation__gameover="" beat="" render-order="">
    <a-entity mixin="gameoverAnimation beatBlock" materials="" animation__gameover=""></a-entity>
  </a-entity>
  <a-entity mixin="gameoverAnimation beat arrowBlueBeat" animation__gameover="" beat="" render-order="">
    <a-entity mixin="gameoverAnimation beatBlock" materials="" animation__gameover=""></a-entity>
  </a-entity>
  <a-entity mixin="gameoverAnimation beat arrowBlueBeat" animation__gameover="" beat="" render-order="">
```

The problem is that just serializing this swath of DOM can take a nontrivial part of a frame time, so the act of logging can result in missed frames.

**Comment by modulesio** [comment] 2019-05-29 16:12
Moon rider loads and rides now with `recomposite4`, so closing this in favor of glitch tracking in https://github.com/exokitxr/exokit/issues/1142.

⛱

**Closed by modulesio** 2019-05-29 16:12 UTC
Labels: 3rd party support, awesome, enhancement
