### ISSUE TITLE
Unexpected behavior with Promise.all when Promise is polyfilled by babel-polyfill/core-js.

### ISSUE THREAD

**Issue by ngokevin** [exokitxr/exokit#473] opened 2018-09-15 05:18 UTC
https://github.com/webmixedreality/exokit/pull/470#issuecomment-421528903

https://glitch.com/edit/#!/leaf-anchovy?path=index.html:1:0

Promise.all never resolves.

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hello, WebVR! • A-Frame</title>
    <meta name="description" content="Hello, WebVR! • A-Frame">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.0.0/polyfill.js"></script>
    <script src="https://aframe.io/releases/0.8.2/aframe.min.js"></script>
    <script>
      var promise = new Promise(resolve => {
        setTimeout(() => { resolve(); }, 1000);  
      });
      
      Promise.all([promise]).then(() => { console.log('Promise.all resolved.'); });
    </script>
  </head>
  <body>
    <a-scene background="color: #ECECEC">
      <a-box position="-1 0.5 -3" rotation="0 45 0" color="#4CC3D9" shadow></a-box>
      <a-sphere position="0 1.25 -5" radius="1.25" color="#EF2D5E" shadow></a-sphere>
      <a-cylinder position="1 0.75 -3" radius="0.5" height="1.5" color="#FFC65D" shadow></a-cylinder>
      <a-plane position="0 0 -4" rotation="-90 0 0" width="4" height="4" color="#7BC8A4" shadow></a-plane>
    </a-scene>
  </body>
</html>
```

> With things like this it could betray a different more fundamental issue, such as async resource callbacks not inducing libUV to tick, so I'd rather understand what's happening than forcefully override it.

Source of the polyfill: https://raw.githubusercontent.com/zloirock/core-js/master/packages/core-js/modules/es.promise.js

I see it has some async calls in this microtask library: https://raw.githubusercontent.com/zloirock/core-js/master/packages/core-js/internals/microtask.js and https://raw.githubusercontent.com/zloirock/core-js/master/packages/core-js/internals/task.js

**Comment by modulesio** [comment] 2018-09-15 10:27
It's fixed by adding a [`RejectionHandledEvent`](https://developer.mozilla.org/en-US/docs/Web/API/PromiseRejectionEvent).

However, this polyfill code is quite crazy in its hacks. It looks like _without_ `PromiseRejectionEvent` a promise is actually a `MutationObserver` flush, which succeeds in Chrome but not Exokit.

**Comment by modulesio** [comment] 2018-09-15 10:48
The root bug is that there is a [`MutationObserver` listening to a detached `Text` node](https://github.com/zloirock/core-js/blob/d42976f7af29832cddc04051cb7032057d17ab74/packages/core-js/internals/microtask.js#L38). This is how `Promise.then` is implemented in the polyfill.

That would most likely make this a regression from https://github.com/webmixedreality/exokit/pull/379/files#diff-9bb39a4c33c894891cba9b6d2008ca65R158.

**Comment by ngokevin** [comment] 2018-09-15 12:12
#379 is correct in that non-attached nodes should not queue *childList* records (see comparison case https://flint-language.glitch.me/). The polyfill queues `characterData` record so perhaps that makes sense it should fire even on non-attached nodes.

**Comment by modulesio** [comment] 2018-09-15 13:04
Isn't [that test case](https://github.com/webmixedreality/exokit/pull/379/files#diff-08f7fd7daa63d02d9573d269c6f5efd3R288) failing in chrome?

I copy-pasted it here: https://glitch.com/edit/#!/chestnut-crocodile

All three cases seem to get triggered for non-attached nodes:

<img width="237" alt="capture3" src="https://user-images.githubusercontent.com/6926057/45586444-8c7efa00-b8c5-11e8-9eb0-5707a1a6f53d.PNG">

**Comment by ngokevin** [comment] 2018-09-15 23:17
Perhaps it should only do the ownerDocument check if the document is what is being observed.

**Closed as completed** 2018-09-16 01:26 UTC
Labels: bug
