### ISSUE TITLE
TypeError: Cannot read property 'supportsSession' of null

### ISSUE THREAD

**Issue by arpu** [exokitxr/exokit#761] opened 2019-01-25 02:47 UTC
with latest aframe master i get 
TypeError: Cannot read property 'supportsSession' of null
    at /main.3ff4ebd95ae43cb0dd12.bundle.js:2:152597
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
core:schema:warn Unknown property `enabled` for component/system `isvr-scene`. 
Bugsnag:  Encountered an uncaught error, terminating…
TypeError: Cannot read property 'supportsSession' of null
    at /main.3ff4ebd95ae43cb0dd12.bundle.js:2:152597
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

exokit 0.0.512

https://github.com/aframevr/aframe/blob/ec8ccb8817157014a06bd77514582ab34dbfc650/src/utils/device.js#L6

**Comment by modulesio** [comment] 2019-01-25 02:51
With the above were we expecting a XR device to be detected+returned?

**Comment by arpu** [comment] 2019-01-25 02:53
ah ok i tested on linux without steamvr or any device

**Comment by modulesio** [comment] 2019-01-25 02:54
If it was expected to throw and continue running, we might still have unintended behavior though...

**Comment by shaneharris** [comment] 2019-02-01 22:33
@arpu without a device or steamVR you could try with the flag `-x none` 

i.e. `node . -x none https://example.com`

**Comment by modulesio** [comment] 2019-06-14 07:30
This should be resolved with the current WebXR version in Exokit.

**Closed by modulesio** 2019-06-14 07:30 UTC
Labels: bug
